export const SUPPORTED_LOCALES = ["de", "en"] as const;
export type Locale = typeof SUPPORTED_LOCALES[number];

export interface LabelDef {
  group: string;
  de: string;
}

export const labelDefaults: Record<string, LabelDef> = {
  "welcome.eyebrow":           { group: "welcome", de: "KI-Sichtbarkeit & SEO-Analyse" },
  "welcome.headline_pre":      { group: "welcome", de: "Wie gut findet" },
  "welcome.headline_post":     { group: "welcome", de: "Ihre Website?" },
  "welcome.subline":           { group: "welcome", de: "Der GAIO Analyzer untersucht Ihre B2B-Website auf LLM-Auffindbarkeit und klassische SEO-Grundlagen — und zeigt, was geändert werden muss, damit KI-Systeme Ihr Unternehmen empfehlen." },
  "welcome.label_company":     { group: "welcome", de: "Unternehmensname" },
  "welcome.placeholder_company": { group: "welcome", de: "Muster GmbH" },
  "welcome.placeholder_url":   { group: "welcome", de: "z. B. domain.de oder www.domain.de" },
  "welcome.btn_start":         { group: "welcome", de: "Analyse starten →" },
  "welcome.prefill_prefix":    { group: "welcome", de: "Oder" },
  "welcome.prefill_link":      { group: "welcome", de: "mit KI vorausfüllen" },
  "welcome.prefill_suffix":    { group: "welcome", de: "— Zielgruppen & Wettbewerber werden automatisch ermittelt." },
  "welcome.tile1_title":       { group: "welcome", de: "LLM-Sichtbarkeit messen" },
  "welcome.tile1_desc":        { group: "welcome", de: "Wir simulieren, wie ChatGPT, Gemini und Claude Ihre Website wahrnehmen — und wo Informationen fehlen." },
  "welcome.tile2_title":       { group: "welcome", de: "Wettbewerb vergleichen" },
  "welcome.tile2_desc":        { group: "welcome", de: "Sehen Sie sofort, ob Konkurrenten in denselben KI-Antworten auftauchen — und warum." },
  "welcome.tile3_title":       { group: "welcome", de: "Priorisierte Maßnahmen" },
  "welcome.tile3_desc":        { group: "welcome", de: "Kritisch, hoher Hebel, nachgeordnet — klare Empfehlungen direkt aus der Analyse." },
  "welcome.preview_label":     { group: "welcome", de: "Beispiel-Ergebnis" },
  "welcome.preview_grade":     { group: "welcome", de: "Ausbaufähig" },
  "welcome.preview_desc":      { group: "welcome", de: "So sieht ein typisches Ergebnis aus. Technische Grundlagen stimmen oft — aber für KI-Systeme fehlen verwertbare Inhalte, strukturierte Daten und FAQ-Strukturen." },
  "welcome.demo_seo":          { group: "welcome", de: "Techn. SEO" },
  "welcome.demo_schema":       { group: "welcome", de: "Schema.org" },
  "welcome.demo_content":      { group: "welcome", de: "Inhalt" },
  "welcome.demo_llm":          { group: "welcome", de: "LLM" },

  "html.title":               { group: "html", de: "HTML-Analyse" },
  "html.subtitle":            { group: "html", de: "Einzelne HTML-Seite analysieren." },
  "html.info_single_page":    { group: "html", de: "Wenn Sie diesen Weg wählen, wird nur die einzelne Seite analysiert, die Sie hier bereitstellen. Crawler-abhängige Module werden übersprungen." },
  "html.tab_code":            { group: "html", de: "Code einfügen" },
  "html.tab_upload":          { group: "html", de: "Datei hochladen" },
  "html.placeholder_code":    { group: "html", de: "HTML-Code hier einfügen..." },
  "html.drop_title":          { group: "html", de: "Datei hierher ziehen" },
  "html.drop_subtitle":       { group: "html", de: "oder klicken zum Auswählen" },
  "html.btn_replace":         { group: "html", de: "Ersetzen" },
  "html.btn_start":           { group: "html", de: "Analyse starten" },
  "html.error_file_type":     { group: "html", de: "Nur .html und .htm Dateien werden akzeptiert." },
  "html.error_empty":         { group: "html", de: "Bitte HTML-Code einfügen oder eine Datei hochladen." },
  "html.error_start_failed":  { group: "html", de: "Analyse konnte nicht gestartet werden. Bitte erneut versuchen." },

  "nav.domain_analyse": { group: "nav", de: "Domainanalyse – Basisdaten" },
  "nav.html_analyse":   { group: "nav", de: "HTML-Analyse" },
  "nav.ergebnisse":     { group: "nav", de: "Ergebnisse" },
  "nav.faq":            { group: "nav", de: "FAQ / So funktioniert's" },
  "nav.kontakt":        { group: "nav", de: "Kontakt" },
  "nav.einstellungen":  { group: "nav", de: "Einstellungen" },
  "nav.vergleich":      { group: "nav", de: "Vergleich" },
  "nav.login":          { group: "nav", de: "Login" },
  "nav.server":         { group: "nav", de: "Server" },
  "nav.menu_open":      { group: "nav", de: "Menü öffnen" },

  "domain.subtitle":               { group: "domain", de: "Website crawlen und alle 7 Analysemodule ausführen." },
  "domain.section_company":        { group: "domain", de: "Unternehmen & Website" },
  "domain.label_company":          { group: "domain", de: "Unternehmensname" },
  "domain.tooltip_company":        { group: "domain", de: "Bitte geben Sie die korrekte Unternehmensbezeichnung ein" },
  "domain.label_url":              { group: "domain", de: "Website-URL" },
  "domain.tooltip_url":            { group: "domain", de: "Bitte Ihre hier zu analysierende Website eintragen" },
  "domain.prefill_pending":        { group: "domain", de: "KI analysiert Unternehmen…" },
  "domain.btn_prefill":            { group: "domain", de: "Mit KI vorausfüllen" },
  "domain.prefill_hint":           { group: "domain", de: "KI schlägt Zielgruppen und Wettbewerber automatisch vor —" },
  "domain.prefill_manual":         { group: "domain", de: "manuell ausfüllen" },
  "domain.btn_switch_to_ai":       { group: "domain", de: "← Mit KI vorausfüllen" },
  "domain.pages_title":            { group: "domain", de: "Zu analysierende Unterseiten" },
  "domain.pages_desc":             { group: "domain", de: "Automatisch beim letzten Crawl erkannt. Sie können URLs bearbeiten, neue hinzufügen und die Auswahl anpassen." },
  "domain.pages_count":            { group: "domain", de: "{selected} von {total} ausgewählt" },
  "domain.pages_deselect_all":     { group: "domain", de: "Alle abwählen" },
  "domain.pages_select_all":       { group: "domain", de: "Alle auswählen" },
  "domain.aria_confirm":           { group: "domain", de: "Bestätigen" },
  "domain.aria_cancel":            { group: "domain", de: "Abbrechen" },
  "domain.aria_edit_url":          { group: "domain", de: "URL bearbeiten" },
  "domain.pages_show_less":        { group: "domain", de: "Weniger anzeigen" },
  "domain.pages_show_more":        { group: "domain", de: "{n} weitere anzeigen" },
  "domain.pages_add_url":          { group: "domain", de: "URL hinzufügen" },
  "domain.prefill_success":        { group: "domain", de: "KI-Vorschläge wurden eingefügt. Bitte überprüfen und bei Bedarf anpassen." },
  "domain.prefill_crawl_failed":   { group: "domain", de: "⚠ Website konnte nicht gecrawlt werden — Vorschläge basieren nur auf dem Unternehmensnamen." },
  "domain.prefill_products_label": { group: "domain", de: "Erkannte Produkte / Leistungen:" },
  "domain.section_competitors":    { group: "domain", de: "Wettbewerber-Domains" },
  "domain.tooltip_competitors":    { group: "domain", de: "Die Website-Adresse/n Ihrer wichtigsten Wettbewerber" },
  "domain.aria_open_website":      { group: "domain", de: "Website öffnen" },
  "domain.placeholder_competitor": { group: "domain", de: "z. B. wettbewerber.de" },
  "domain.tooltip_url_unverified": { group: "domain", de: "URL konnte nicht automatisch verifiziert werden — bitte prüfen" },
  "domain.aria_url_verified":      { group: "domain", de: "URL verifiziert" },
  "domain.aria_url_unverified":    { group: "domain", de: "URL nicht verifiziert" },
  "domain.aria_remove":            { group: "domain", de: "Entfernen" },
  "domain.btn_add_competitor":     { group: "domain", de: "Weiteren Wettbewerber hinzufügen" },
  "domain.section_personas":       { group: "domain", de: "Zielgruppen / Käuferpersonas" },
  "domain.tooltip_personas":       { group: "domain", de: "Hier Ihre Zielbranchen und Zielpersonen (Einkäufer, Projektingenieure, R+D…) eintragen" },
  "domain.placeholder_personas":   { group: "domain", de: "z. B. Einkaufsleiter in der Automobilindustrie, Projektingenieure im Maschinenbau, F&E-Verantwortliche..." },
  "domain.error_company_required": { group: "domain", de: "Bitte Unternehmensname eingeben" },
  "domain.error_url_required":     { group: "domain", de: "Bitte Website-URL eingeben" },
  "domain.error_url_invalid":      { group: "domain", de: "Bitte eine gültige URL eingeben (https://...)" },
  "domain.error_prefill_failed":   { group: "domain", de: "KI-Vorausfüllung fehlgeschlagen. Bitte füllen Sie die Felder manuell aus." },

  "faq.subtitle":                    { group: "faq", de: "Alles über die Analyse-Methodik und Score-Interpretation." },
  "faq.section_what":                { group: "faq", de: "Was analysiert dieses Tool?" },
  "faq.what_desc":                   { group: "faq", de: "GAIO Analyzer untersucht B2B-Industriewebsites auf ihre Auffindbarkeit durch KI-Sprachmodelle (LLMs) sowie auf klassische SEO-Grundlagen. Ziel ist es, konkrete Handlungsempfehlungen zu liefern, die sowohl die Suchmaschinen-Indexierung als auch die Zitierwahrscheinlichkeit durch KI-Assistenten wie ChatGPT, Gemini oder Perplexity erhöhen." },
  "faq.section_modules":             { group: "faq", de: "Die Analyse-Module im Überblick" },
  "faq.col_module":                  { group: "faq", de: "Modul" },
  "faq.col_checked":                 { group: "faq", de: "Was wird geprüft" },
  "faq.col_why":                     { group: "faq", de: "Warum es wichtig ist" },
  "faq.mod1_name":                   { group: "faq", de: "Technische SEO-Basis" },
  "faq.mod1_check":                  { group: "faq", de: "HTTP-Antwortzeit, HTTPS, robots.txt, llms.txt, Sitemap (.xml oder /sitemap<sup>*</sup>), Canonical-Tags, hreflang, Meta-Titel und -Beschreibungen, Alt-Texte, Mobile-Viewport" },
  "faq.mod1_why":                    { group: "faq", de: "Grundvoraussetzung für Indexierung durch Suchmaschinen und LLM-Crawler" },
  "faq.mod2_name":                   { group: "faq", de: "Strukturierte Daten (Schema.org)" },
  "faq.mod2_check":                  { group: "faq", de: "JSON-LD, Microdata, RDFa — Typen: Organization, Product, FAQPage, BreadcrumbList u.a." },
  "faq.mod2_why":                    { group: "faq", de: "Maschinenlesbare Fakten erhöhen die Wahrscheinlichkeit, dass LLMs korrekte und vollständige Antworten generieren" },
  "faq.mod3_name":                   { group: "faq", de: "Heading-Struktur" },
  "faq.mod3_check":                  { group: "faq", de: "H1/H2/H3-Hierarchie, Keyword-Präsenz in Überschriften" },
  "faq.mod3_why":                    { group: "faq", de: "Strukturierte Inhalte werden von LLMs bevorzugt als Quellen verarbeitet" },
  "faq.mod4_name":                   { group: "faq", de: "Inhaltliche Relevanz (KI-gestützt)" },
  "faq.mod4_check":                  { group: "faq", de: "Vorhandensein von Anwendungsszenarien, technischer Tiefe, Käufer-Fragetypen" },
  "faq.mod4_why":                    { group: "faq", de: "LLMs zitieren Seiten häufiger, wenn diese echte Nutzerfragen vollständig beantworten" },
  "faq.mod5_name":                   { group: "faq", de: "FAQ-Qualität" },
  "faq.mod5_check":                  { group: "faq", de: "Erkannte FAQ-Strukturen, Frageformulierung, Antworttiefe" },
  "faq.mod5_why":                    { group: "faq", de: "FAQPage-Schema ist einer der stärksten Einzelhebel für LLM-Sichtbarkeit" },
  "faq.mod6_name":                   { group: "faq", de: "LLM-Sichtbarkeitssimulation" },
  "faq.mod6_check":                  { group: "faq", de: "Generierte Käuferfragen + prognostizierte Antwortqualität auf Basis des vorhandenen Contents" },
  "faq.mod6_why":                    { group: "faq", de: "Zeigt direkt, welche Informationslücken LLMs bei Anfragen zu Ihrem Unternehmen haben" },
  "faq.sitemap_title":               { group: "faq", de: "sitemap.xml vs. /sitemap — was wird geprüft und warum beides relevant ist" },
  "faq.sitemap_desc":                { group: "faq", de: "Der GAIO Analyzer sucht zuerst nach einer maschinenlesbaren sitemap.xml (inkl. sitemap_index.xml sowie in robots.txt deklarierten Sitemap-Pfaden). Falls keine XML-Sitemap gefunden wird, sucht er nach einer HTML-Sitemap unter gängigen Pfaden wie /sitemap, /sitemap.html oder /seitenübersicht." },
  "faq.sitemap_col_criterion":       { group: "faq", de: "Kriterium" },
  "faq.sitemap_row_purpose_label":   { group: "faq", de: "Zweck" },
  "faq.sitemap_row_purpose_xml":     { group: "faq", de: "Maschinenlesbare Übergabe an Crawler; enthält lastmod, priority, changefreq" },
  "faq.sitemap_row_purpose_html":    { group: "faq", de: "HTML-Seite mit internen Links zu allen wichtigen Seiten; für Menschen und Crawler lesbar" },
  "faq.sitemap_row_google_label":    { group: "faq", de: "Google / Search Console" },
  "faq.sitemap_row_google_xml":      { group: "faq", de: "✅ Direkt einreichbar; Indexierungsstatus in Search Console sichtbar" },
  "faq.sitemap_row_google_html":     { group: "faq", de: "❌ Nicht einreichbar; kann aber selbst indexiert werden" },
  "faq.sitemap_row_links_label":     { group: "faq", de: "Interne Verlinkung" },
  "faq.sitemap_row_links_xml":       { group: "faq", de: "❌ Wird nicht als Linkquelle gewertet" },
  "faq.sitemap_row_links_html":      { group: "faq", de: "✅ Interne Links zählen als Linkgraph und stärken PageRank-Verteilung" },
  "faq.sitemap_row_llm_train_label": { group: "faq", de: "LLM-Training-Crawler" },
  "faq.sitemap_row_llm_train_xml":   { group: "faq", de: "⚠️ Wird von manchen Crawlern (z.B. Common Crawl) gelesen, aber nicht als Content aufgenommen" },
  "faq.sitemap_row_llm_train_html":  { group: "faq", de: "✅ HTML-Links werden direkt als Crawl-Einstiegspunkte verwertet — für Link-Following-Crawler direkter verwertbar" },
  "faq.sitemap_row_rag_label":       { group: "faq", de: "LLM-Live-Retrieval (RAG)" },
  "faq.sitemap_row_rag_xml":         { group: "faq", de: "✅ Bessere XML-Indexierung = mehr Seiten im Suchindex = mehr Zitierchancen" },
  "faq.sitemap_row_rag_html":        { group: "faq", de: "✅ Kann selbst gecrawlt und als Linking-Hub genutzt werden" },
  "faq.sitemap_row_scale_label":     { group: "faq", de: "Skalierung" },
  "faq.sitemap_row_scale_xml":       { group: "faq", de: "✅ Bis 50.000 URLs; erweiterbar via Sitemap-Index; Spezialformate für Bilder, Videos, News" },
  "faq.sitemap_row_scale_html":      { group: "faq", de: "⚠️ Bei großen Sites schwer wartbar; kein Ersatz für sitemap.xml" },
  "faq.sitemap_recommendation":      { group: "faq", de: "Empfehlung: sitemap.xml und HTML-Sitemap schließen sich nicht aus — sie erfüllen unterschiedliche Funktionen. sitemap.xml ist für die Google-Indexierung unverzichtbar. Eine gepflegte HTML-Sitemap (/sitemap) hat zusätzlichen Wert als internes Verlinkungshub und als Crawl-Einstiegspunkt für LLM-Trainingscrawler — aber nur als Ergänzung, nicht als Ersatz." },
  "faq.section_weights":             { group: "faq", de: "Score-Gewichtung (Gesamt-GAIO-Score)" },
  "faq.weight_schema":               { group: "faq", de: "Strukturierte Daten" },
  "faq.weight_content":              { group: "faq", de: "Inhaltliche Relevanz" },
  "faq.weight_llm":                  { group: "faq", de: "LLM-Sichtbarkeit" },
  "faq.weight_tech":                 { group: "faq", de: "Technische SEO-Basis" },
  "faq.weight_faq":                  { group: "faq", de: "FAQ-Qualität" },
  "faq.weight_heading":              { group: "faq", de: "Heading-Struktur" },
  "faq.section_scores":              { group: "faq", de: "Score-Interpretation" },
  "faq.score_col_score":             { group: "faq", de: "Score" },
  "faq.score_col_rating":            { group: "faq", de: "Bewertung" },
  "faq.score_col_meaning":           { group: "faq", de: "Bedeutung" },
  "faq.score_critical_label":        { group: "faq", de: "Kritisch" },
  "faq.score_critical_desc":         { group: "faq", de: "Grundlegende Defizite — LLMs können diese Website kaum als Quelle nutzen" },
  "faq.score_improving_label":       { group: "faq", de: "Ausbaufähig" },
  "faq.score_improving_desc":        { group: "faq", de: "Technische Basis vorhanden, aber inhaltliche Lücken limitieren die LLM-Sichtbarkeit erheblich" },
  "faq.score_solid_label":           { group: "faq", de: "Solide" },
  "faq.score_solid_desc":            { group: "faq", de: "Gute Ausgangsbasis — gezielte Maßnahmen können die Sichtbarkeit spürbar steigern" },
  "faq.score_strong_label":          { group: "faq", de: "Stark" },
  "faq.score_strong_desc":           { group: "faq", de: "Überdurchschnittlich gut aufgestellt; Feinoptimierung empfohlen" },
  "faq.score_excellent_label":       { group: "faq", de: "Exzellent" },
  "faq.score_excellent_desc":        { group: "faq", de: "Best-in-class LLM-Readiness" },
  "faq.section_priority":            { group: "faq", de: "Empfehlungs-Priorisierung" },
  "faq.priority_desc":               { group: "faq", de: "Jede Analyse erzeugt priorisierte Handlungsempfehlungen in drei Stufen:" },
  "faq.priority_critical_desc":      { group: "faq", de: "Fundamentale Fehler, die sofort behoben werden müssen (z. B. fehlendes HTTPS, keine strukturierten Daten, kein H1)." },
  "faq.priority_high_label":         { group: "faq", de: "Hoher Hebel" },
  "faq.priority_high_desc":          { group: "faq", de: "Maßnahmen mit dem größten Wirkungspotenzial (z. B. fehlende FAQPage-Schema, dünne Produktbeschreibungen, fehlende Anwendungsszenarien)." },
  "faq.priority_low_label":          { group: "faq", de: "Nachgeordnet" },
  "faq.priority_low_desc":           { group: "faq", de: "Optimierungen für nach der Erstbereinigung (z. B. Meta-Description-Länge, Alt-Text-Lücken)." },
  "faq.section_accuracy":            { group: "faq", de: "Hinweise zur Genauigkeit" },
  "faq.accuracy_desc":               { group: "faq", de: "Scores basieren auf einer automatisierten Analyse und stellen Annäherungswerte dar. Wettbewerber-Scores beruhen auf einer Stichprobe (Startseite + max. 3 Unterseiten). Die LLM-Sichtbarkeitssimulation verwendet Claude (Anthropic) und spiegelt keine garantierten Rankingfaktoren wider. Alle Empfehlungen sollten mit einem Experten validiert werden." },

  "contact.subtitle":  { group: "contact", de: "Ihr Ansprechpartner für GAIO Analyzer und LLM-Sichtbarkeit." },
  "contact.btn_email": { group: "contact", de: "E-Mail schreiben" },

  "shared.loading_title":      { group: "shared", de: "Analyse wird geladen…" },
  "shared.loading_wait":       { group: "shared", de: "Bitte warten…" },
  "shared.not_found_title":    { group: "shared", de: "Nicht gefunden" },
  "shared.not_found_box_title":{ group: "shared", de: "Freigabe nicht gefunden" },
  "shared.not_found_box_text": { group: "shared", de: "Dieser Link existiert nicht oder wurde noch nie erstellt." },
  "shared.expired_title":      { group: "shared", de: "Freigabe abgelaufen" },
  "shared.expired_box_text":   { group: "shared", de: "Dieser Link ist nicht mehr gültig. Bitte wende dich an den Absender für einen neuen Link." },
  "shared.disabled_title":     { group: "shared", de: "Analyse-Sharing deaktiviert" },
  "shared.disabled_box_title": { group: "shared", de: "Sharing deaktiviert" },
  "shared.disabled_box_text":  { group: "shared", de: "Das Teilen von Analysen ist auf diesem System deaktiviert." },
  "shared.error_title":        { group: "shared", de: "Fehler" },
  "shared.error_box_title":    { group: "shared", de: "Fehler beim Laden" },
  "shared.error_box_text":     { group: "shared", de: "Der Analyse-Report konnte nicht geladen werden. Bitte versuche es später erneut." },
  "shared.analyse_prefix":     { group: "shared", de: "Analyse: {domain}" },
  "shared.iframe_title":       { group: "shared", de: "GAIO Analyse — {domain}" },
  "shared.footer_shared_by":   { group: "shared", de: "Dieser Report wurde geteilt von {company}." },
  "shared.footer_valid_until": { group: "shared", de: "Gültig bis {date}." },

  "settings.subtitle":        { group: "settings", de: "App-Konfiguration und Darstellung." },
  "settings.section_display": { group: "settings", de: "Darstellung" },
  "settings.color_mode":      { group: "settings", de: "Farbmodus" },
  "settings.theme_light":     { group: "settings", de: "Hell" },
  "settings.theme_dark":      { group: "settings", de: "Dunkel" },
  "settings.theme_system":    { group: "settings", de: "Systemeinstellung" },
  "settings.theme_default":   { group: "settings", de: "(Standard)" },

  "compare.dim_technical":       { group: "compare", de: "Technisches SEO" },
  "compare.dim_schema":          { group: "compare", de: "Strukturierte Daten" },
  "compare.dim_headings":        { group: "compare", de: "Überschriften" },
  "compare.dim_content":         { group: "compare", de: "Content-Relevanz" },
  "compare.dim_faq":             { group: "compare", de: "FAQ-Qualität" },
  "compare.dim_llm":             { group: "compare", de: "LLM-Auffindbarkeit" },
  "compare.delta_major_up":      { group: "compare", de: "Deutliche Verbesserung — der GAIO Score hat sich signifikant erhöht." },
  "compare.delta_pos":           { group: "compare", de: "Positive Entwicklung — sichtbarer Fortschritt in der LLM-Auffindbarkeit und SEO-Qualität." },
  "compare.delta_minor_up":      { group: "compare", de: "Leichte Verbesserung — kleinere Optimierungen zeigen erste Wirkung." },
  "compare.delta_stable":        { group: "compare", de: "Keine Änderung — der GAIO Score ist stabil geblieben." },
  "compare.delta_minor_down":    { group: "compare", de: "Leichter Rückgang — geringfügige Verschlechterung, Monitoring empfohlen." },
  "compare.delta_neg":           { group: "compare", de: "Negativer Trend — relevante Verschlechterung, Handlungsbedarf prüfen." },
  "compare.delta_major_down":    { group: "compare", de: "Deutlicher Rückgang — der GAIO Score hat sich signifikant verschlechtert." },
  "compare.title":               { group: "compare", de: "Analyse-Vergleich" },
  "compare.subtitle":            { group: "compare", de: "Vergleiche die aktuelle Analyse mit einer früheren und sieh die Entwicklung auf einen Blick." },
  "compare.label_current":       { group: "compare", de: "Aktuelle Analyse" },
  "compare.label_comparison":    { group: "compare", de: "Vergleichsanalyse" },
  "compare.current_ref_label":   { group: "compare", de: "Aktuelle Analyse (Referenz)" },
  "compare.loading_current":     { group: "compare", de: "Lade aktuelle Analyse…" },
  "compare.current_ref_note":    { group: "compare", de: "Diese Analyse wird als Referenz verwendet." },
  "compare.no_analysis_loaded":  { group: "compare", de: "Keine Analyse geladen." },
  "compare.select_comparison":   { group: "compare", de: "Vergleichsanalyse auswählen" },
  "compare.tab_protokoll":       { group: "compare", de: "Aus Protokoll laden" },
  "compare.tab_upload":          { group: "compare", de: "HTML-Datei hochladen" },
  "compare.loading":             { group: "compare", de: "Wird geladen…" },
  "compare.btn_load_log":        { group: "compare", de: "Protokoll laden" },
  "compare.log_empty":           { group: "compare", de: "Keine weiteren abgeschlossenen Analysen im Protokoll vorhanden." },
  "compare.select_label":        { group: "compare", de: "Analyse auswählen" },
  "compare.select_placeholder":  { group: "compare", de: "— Analyse auswählen —" },
  "compare.log_option":          { group: "compare", de: "{domain} · {date} · Score: {score}{company}" },
  "compare.btn_show":            { group: "compare", de: "Vergleich anzeigen" },
  "compare.badge_view":          { group: "compare", de: "Vergleichsansicht" },
  "compare.btn_reset":           { group: "compare", de: "Zurücksetzen" },
  "compare.change_title":        { group: "compare", de: "Veränderung GAIO Score" },
  "compare.col_dimension":       { group: "compare", de: "Dimension" },
  "compare.col_comparison":      { group: "compare", de: "Vergleich" },
  "compare.col_current":         { group: "compare", de: "Aktuell" },
  "compare.error_no_embed_data": { group: "compare", de: "Diese Datei enthält keine maschinenlesbaren Analysedaten." },
  "compare.file_loaded":         { group: "compare", de: "Geladen ✓" },
  "compare.file_drop_hint":      { group: "compare", de: "HTML-Export hier ablegen oder klicken zum Auswählen" },
  "compare.file_drop_subhint":   { group: "compare", de: "Nur .html-Dateien aus dem GAIO Analyzer Export" },

  "progress.module_crawling":         { group: "progress", de: "Crawling Website" },
  "progress.module_technical_seo":    { group: "progress", de: "Technisches SEO" },
  "progress.module_schema":           { group: "progress", de: "Schema.org / Strukturierte Daten" },
  "progress.module_headings":         { group: "progress", de: "Heading-Struktur" },
  "progress.module_content":          { group: "progress", de: "Inhaltliche Relevanz (KI-Analyse)" },
  "progress.module_faq":              { group: "progress", de: "FAQ-Qualität" },
  "progress.module_llm":              { group: "progress", de: "LLM-Auffindbarkeit" },
  "progress.module_competitor":       { group: "progress", de: "Wettbewerbsvergleich" },
  "progress.module_recommendations":  { group: "progress", de: "Empfehlungen generieren" },
  "progress.title_failed":            { group: "progress", de: "Analyse fehlgeschlagen" },
  "progress.title_running":           { group: "progress", de: "Analyse für {target} läuft…" },
  "progress.crawling_url":            { group: "progress", de: "Crawle {url}" },
  "progress.processing_data":         { group: "progress", de: "Verarbeite Daten…" },
  "progress.initializing":            { group: "progress", de: "Initialisierung…" },
  "progress.para_time_pre":           { group: "progress", de: "Die von mir jetzt durchzuführende " },
  "progress.para_time_emph1":         { group: "progress", de: "Analyse" },
  "progress.para_time_mid":           { group: "progress", de: " ist wirklich sehr umfangreich und " },
  "progress.para_time_emph2":         { group: "progress", de: "kann bis zu 10 Minuten dauern" },
  "progress.para_time_post":          { group: "progress", de: ". Insbesondere ganz am Ende — bei den \u201EEmpfehlungen generieren\u201C — wird Ihre Geduld wahrscheinlich wirklich auf die Probe gestellt! Aber gerade da soll ich ja auch besonders genau sein, oder?" },
  "progress.para_never_give_up":      { group: "progress", de: "Aber: Nicht verzweifeln — bisher habe ich noch jede Analyse zu Ende gebracht!" },
  "progress.para_coffee":             { group: "progress", de: "Wie wäre es, wenn Sie sich in der Zwischenzeit einen Kaffee, Tee oder — je nach Tageszeit — ein anderes Getränk holen und mich kurz arbeiten lassen?" },
  "progress.para_dont_close_prefix":  { group: "progress", de: "Wichtig:" },
  "progress.para_dont_close_body":    { group: "progress", de: " Bitte schließen Sie diesen Tab oder dieses Fenster auf keinen Fall, da ich sonst ebenfalls gehe … und dann müssten wir noch einmal von vorne anfangen." },
  "progress.hints_label":             { group: "progress", de: "Hinweise:" },

  "results.traffic_good":               { group: "results", de: "Gut" },
  "results.traffic_acceptable":         { group: "results", de: "Akzeptabel" },
  "results.traffic_critical":           { group: "results", de: "Kritisch" },
  "results.tooltip_info_prefix":        { group: "results", de: "Info: {label}" },
  "results.analyzed_pages_heading":     { group: "results", de: "Analysierte Seiten" },
  "results.delta_advantage":            { group: "results", de: "Ihr Vorteil" },
  "results.delta_catchup":              { group: "results", de: "Aufholbedarf" },
  "results.delta_even":                 { group: "results", de: "Gleichstand" },
  "results.crawled_pages_heading":      { group: "results", de: "Gecrawlte Seiten ({count} Seiten)" },
  "results.hreflang_title":             { group: "results", de: "Erkannte Sprachvarianten der Website" },
  "results.hreflang_empty":             { group: "results", de: "Keine Sprachvarianten dieser Website gefunden." },
  "results.hreflang_count_note":        { group: "results", de: "{count} Sprachvarianten erkannt — URLs gespeichert für spätere Mehrsprachenanalyse" },

  "results.score_strong":               { group: "results", de: "Stark" },
  "results.score_solid":                { group: "results", de: "Solide" },
  "results.score_developing":           { group: "results", de: "Ausbaufähig" },
  "results.score_critical":             { group: "results", de: "Kritisch" },
  "results.competitor_unreachable":     { group: "results", de: "Nicht erreichbar" },
  "results.competitor_unreachable_desc":{ group: "results", de: "Diese Domain konnte nicht gecrawlt werden (Timeout, Zugriffsblockierung oder ungültige URL)." },
  "results.metric_technical_seo":       { group: "results", de: "Technisches SEO" },
  "results.metric_schema":              { group: "results", de: "Schema.org" },
  "results.metric_content":             { group: "results", de: "Inhaltliche Relevanz" },
  "results.metric_headings":            { group: "results", de: "Heading-Struktur" },
  "results.metric_faq":                 { group: "results", de: "FAQ-Qualität" },
  "results.table_metric":               { group: "results", de: "Metrik" },
  "results.table_your_site":            { group: "results", de: "Ihre Seite" },
  "results.table_competitor":           { group: "results", de: "Wettbewerber" },
  "results.table_delta_rating":         { group: "results", de: "Delta / Bewertung" },
  "results.llm_note":                   { group: "results", de: "LLM-Sichtbarkeit wird nur für die Hauptdomain vollständig analysiert" },
  "results.finding_better":             { group: "results", de: "Was macht dieser Wettbewerber besser?" },
  "results.finding_advantage":          { group: "results", de: "Ihr klarer Vorteil" },
  "results.finding_recommendation":     { group: "results", de: "Konkrete Empfehlung" },
  "results.score_basis_prefix":         { group: "results", de: "Score-Basis:" },
  "results.competitor_multi_pages":     { group: "results", de: "{count} gecrawlte Seiten" },
  "results.competitor_single_page":     { group: "results", de: "Einzelseiten-Stichprobe (Startseite)" },
  "results.llm_no_source_found":        { group: "results", de: "Keine passende Quellseite gefunden" },

  "results.tab_details":                { group: "results", de: "Details" },
  "results.tab_llm":                    { group: "results", de: "LLM-Auffindbarkeit" },
  "results.tab_competitors":            { group: "results", de: "Wettbewerb" },
  "results.tab_recommendations":        { group: "results", de: "Empfehlungen" },
  "results.competitor_overview_title":  { group: "results", de: "Gesamt-Score Übersicht" },
  "results.chart_score_label":          { group: "results", de: "Score" },
  "results.your_site_highlighted":      { group: "results", de: "Ihre Seite ist blau hervorgehoben." },
  "results.competitors_unavailable_html": { group: "results", de: "Wettbewerbsvergleich nicht verfügbar im HTML-Modus." },
  "results.no_competitor_urls":         { group: "results", de: "Keine Wettbewerber-URLs angegeben." },
  "results.rec_critical_heading":       { group: "results", de: "Kritisch ({count})" },
  "results.rec_high_heading":           { group: "results", de: "Hoher Hebel ({count})" },
  "results.rec_secondary_heading":      { group: "results", de: "Sekundär ({count})" },
  "results.no_recommendations":         { group: "results", de: "Keine Empfehlungen generiert." },

  "results.llm_grid_part_a":            { group: "results", de: "Auffindbarkeit (Teil A \u00B7 70%)" },
  "results.llm_grid_part_b":            { group: "results", de: "Informationstiefe (Teil B \u00B7 30%)" },
  "results.llm_grid_total":             { group: "results", de: "Gesamt (gewichtet)" },
  "results.llm_avg_rating":             { group: "results", de: "\u00D8 {value} / 5" },
  "results.llm_part_a_label":           { group: "results", de: "Teil A \u2014 Problem-/Kategorie-Fragen (ohne Markenname)" },
  "results.llm_part_b_label":           { group: "results", de: "Teil B \u2014 Marken-Verifikationsfragen" },
  "results.llm_part_a_explainer":       { group: "results", de: "Buyer kennt das Unternehmen NICHT \u2014 testet, ob die Seite in Kategorie- und Problemfragen auftaucht." },
  "results.llm_part_b_explainer":       { group: "results", de: "Buyer kennt die Marke bereits \u2014 pr\u00FCft, wie tief und konkret die Seite Markenfragen beantwortet." },
  "results.llm_fallback_title":         { group: "results", de: "LLM-Auffindbarkeits-Simulation (Score: {score}/100)" },
  "results.llm_no_data":                { group: "results", de: "Keine LLM-Daten verf\u00FCgbar." },

  "results.technical_metrics_title":    { group: "results", de: "Technische SEO-Metriken" },
  "results.technical_details_title":    { group: "results", de: "Technische Details" },
  "results.metric_response_time":       { group: "results", de: "Antwortzeit" },
  "results.metric_response_time_tooltip": { group: "results", de: "Die Antwortzeit misst, wie lange der Server insgesamt braucht, um eine vollst\u00E4ndige Seite zu liefern. Unter 400 ms gilt als schnell. \u00DCber 800 ms wirkt sich negativ auf SEO und Nutzererfahrung aus." },
  "results.metric_ttfb":                { group: "results", de: "TTFB" },
  "results.metric_ttfb_tooltip":        { group: "results", de: "Time to First Byte (TTFB) misst, wie schnell der Server mit der Auslieferung beginnt \u2014 bevor der Browser die Seite aufgebaut hat. Ein niedriger TTFB (unter 200 ms) zeigt gute Server-Performance. Google nutzt TTFB als Qualit\u00E4tssignal." },
  "results.metric_robots_txt":          { group: "results", de: "robots.txt" },
  "results.metric_sitemap":             { group: "results", de: "Sitemap" },
  "results.metric_llms_txt":            { group: "results", de: "llms.txt" },
  "results.metric_https":               { group: "results", de: "HTTPS" },
  "results.metric_viewport":            { group: "results", de: "Viewport" },
  "results.metric_alt_text":            { group: "results", de: "Alt-Text" },
  "results.metric_canonical_tags":      { group: "results", de: "Canonical Tags" },

  "results.technical_files_title":      { group: "results", de: "Technische Dateien" },
  "results.status_allowed":             { group: "results", de: "Erlaubt" },
  "results.status_blocked":             { group: "results", de: "Gesperrt" },
  "results.status_not_mentioned":       { group: "results", de: "Nicht erw\u00E4hnt" },
  "results.status_found":               { group: "results", de: "gefunden" },
  "results.status_not_found":           { group: "results", de: "nicht gefunden" },
  "results.robots_blocked_prefix":      { group: "results", de: "Kritisch:" },
  "results.robots_blocked_message":     { group: "results", de: "Komplette Sperrung (Disallow: /) f\u00FCr: {agents}" },
  "results.robots_llm_crawler_status":  { group: "results", de: "LLM-Crawler Status" },
  "results.robots_crawl_delay_label":   { group: "results", de: "Crawl-Delay:" },
  "results.robots_sitemap_refs_label":  { group: "results", de: "Sitemap-Referenzen:" },
  "results.robots_user_agents_label":   { group: "results", de: "Erw\u00E4hnte User-Agents:" },
  "results.raw_data_toggle":            { group: "results", de: "Rohdaten anzeigen (erste 500 Zeichen)" },
  "results.robots_not_found":           { group: "results", de: "robots.txt wurde nicht gefunden oder ist nicht erreichbar." },
  "results.sitemap_badge_xml":          { group: "results", de: "XML" },
  "results.sitemap_badge_xml_index":    { group: "results", de: "XML-Index" },
  "results.sitemap_badge_html":         { group: "results", de: "HTML-Sitemap" },
  "results.sitemap_urls_total":         { group: "results", de: "URLs gesamt" },
  "results.sitemap_type_label":         { group: "results", de: "Typ" },
  "results.sitemap_is_index":           { group: "results", de: "Sitemap-Index" },
  "results.sitemap_single":             { group: "results", de: "Einzelne Sitemap" },
  "results.sitemap_crawl_coverage":     { group: "results", de: "Crawl-Abdeckung" },
  "results.sitemap_special_types":      { group: "results", de: "Spezial-Typen" },
  "results.sitemap_type_image":         { group: "results", de: "Bild" },
  "results.sitemap_type_video":         { group: "results", de: "Video" },
  "results.sitemap_oldest_lastmod":     { group: "results", de: "\u00C4lteste Lastmod" },
  "results.sitemap_newest_lastmod":     { group: "results", de: "Neueste Lastmod" },
  "results.sitemap_priority_distribution": { group: "results", de: "Priority-Verteilung" },
  "results.sitemap_found_at":           { group: "results", de: "Gefunden unter" },
  "results.sitemap_links_total":        { group: "results", de: "Verlinkungen gesamt" },
  "results.sitemap_structure_sections": { group: "results", de: "Struktur-Sektionen" },
  "results.sitemap_section_headings":   { group: "results", de: "Sektion-\u00DCberschriften" },
  "results.html_sitemap_warning_pre":   { group: "results", de: "HTML-Sitemaps sind nicht maschinenlesbar \u2014 Suchmaschinen und LLM-Crawler k\u00F6nnen sie nicht automatisch verarbeiten. Erstellen Sie zus\u00E4tzlich eine " },
  "results.html_sitemap_warning_post":  { group: "results", de: "." },
  "results.html_preview_toggle":        { group: "results", de: "HTML-Vorschau (erste 500 Zeichen)" },
  "results.sitemap_none_found":         { group: "results", de: "Keine Sitemap gefunden (weder XML noch HTML)." },
  "results.sitemap_no_detail":          { group: "results", de: "Sitemap erkannt, aber keine Detailanalyse verf\u00FCgbar." },
  "results.llms_missed_chance_label":   { group: "results", de: "Verpasste Chance:" },
  "results.llms_missed_chance_text":    { group: "results", de: "llms.txt ist ein aufkommender Standard, mit dem Website-Betreiber strukturierte Informationen speziell f\u00FCr LLM-Crawler bereitstellen \u2014 \u00E4hnlich wie robots.txt, aber mit inhaltlichem Fokus f\u00FCr KI-Systeme wie ChatGPT, Claude und Perplexity." },
  "results.llms_title_label":           { group: "results", de: "Titel" },
  "results.llms_description_label":     { group: "results", de: "Beschreibung" },
  "results.llms_sections_heading":      { group: "results", de: "Abschnitte ({count})" },
  "results.llms_no_links_in_section":   { group: "results", de: "Keine Links in diesem Abschnitt" },
  "results.llms_linked_pages_count":    { group: "results", de: "{count} verlinkte Seiten" },
  "results.llms_has_description":       { group: "results", de: "\u2713 Beschreibung vorhanden" },
  "results.llms_no_description":        { group: "results", de: "\u2717 Keine Beschreibung" },

  "results.schema_title":               { group: "results", de: "Schema.org / Strukturierte Daten" },
  "results.schema_detected_types_label": { group: "results", de: "Erkannte Typen:" },
  "results.schema_none_found":          { group: "results", de: "Keine strukturierten Daten gefunden" },
  "results.schema_missing_types_label": { group: "results", de: "Fehlende wichtige Typen:" },
  "results.content_relevance_title":    { group: "results", de: "Inhaltliche Relevanz" },

  "results.email_invalid":             { group: "results", de: "Bitte geben Sie eine g\u00FCltige E-Mail-Adresse ein." },
  "results.email_send_failed":         { group: "results", de: "E-Mail konnte nicht gesendet werden. Bitte pr\u00FCfen Sie die Mailserver-Einstellungen." },
  "results.chart_dim_technical":       { group: "results", de: "Techn. SEO" },
  "results.chart_dim_schema":          { group: "results", de: "Schema.org" },
  "results.chart_dim_headings":        { group: "results", de: "Headings" },
  "results.chart_dim_content":         { group: "results", de: "Inhalt" },
  "results.page_title":                { group: "results", de: "Ergebnisse" },
  "results.html_upload_fallback":      { group: "results", de: "HTML-Upload" },
  "results.pages_suffix":              { group: "results", de: "{count} Seiten" },
  "results.pdf_export_loading":        { group: "results", de: "PDF wird erstellt\u2026" },
  "results.pdf_export_button":         { group: "results", de: "Report als PDF exportieren" },
  "results.html_export_loading":       { group: "results", de: "Bereite Export vor\u2026" },
  "results.html_export_button":        { group: "results", de: "Report als HTML exportieren" },
  "results.share_button":              { group: "results", de: "Teilen" },
  "results.rerun_hint_pre":            { group: "results", de: "Basisdaten \u00E4ndern oder neue Analyse starten? \u2192 Wechseln Sie zu " },
  "results.rerun_hint_mid":            { group: "results", de: " oder " },
  "results.rerun_hint_post":           { group: "results", de: "." },
  "results.email_modal_title":         { group: "results", de: "Report per E-Mail senden" },
  "results.email_modal_subtitle":      { group: "results", de: "Geben Sie die Empf\u00E4ngeradresse ein." },
  "results.email_modal_generating":    { group: "results", de: "Der {type}-Report wird generiert und direkt zugestellt." },
  "results.email_sent_prefix":         { group: "results", de: "Report wurde an " },
  "results.email_sent_suffix":         { group: "results", de: " gesendet." },
  "results.sending_loading":           { group: "results", de: "Wird gesendet\u2026" },
  "results.send_button":               { group: "results", de: "Senden" },
  "results.share_modal_title":         { group: "results", de: "Analyse teilen" },
  "results.share_no_log":              { group: "results", de: "Diese Analyse wurde noch nicht im Protokoll gespeichert. Bitte exportieren Sie den Report zuerst als HTML." },
  "results.share_link_created":        { group: "results", de: "Freigabe-Link wurde erstellt:" },
  "results.copy_button_title":         { group: "results", de: "Kopieren" },
  "results.share_valid_until":         { group: "results", de: "G\u00FCltig bis {date}." },
  "results.share_manage_prefix":       { group: "results", de: "Verwalten Sie alle Freigaben unter " },
  "results.share_manage_suffix":       { group: "results", de: "." },
  "results.close_button":              { group: "results", de: "Schlie\u00DFen" },
  "results.share_create_description":  { group: "results", de: "Erstellt einen \u00F6ffentlichen Link zu diesem Analyse-Report." },
  "results.share_expiry_label":        { group: "results", de: "G\u00FCltig f\u00FCr (Tage)" },
  "results.share_creating_loading":    { group: "results", de: "Erstelle\u2026" },
  "results.share_create_button":       { group: "results", de: "Link erstellen" },
  "results.pdf_page_export_failed":    { group: "results", de: "Seite konnte nicht exportiert werden" },
  "results.pdf_export_failed_prefix":  { group: "results", de: "PDF-Export fehlgeschlagen: " },
  "results.pdf_footer_export_date_prefix": { group: "results", de: "/GAIO-Analyzer \u00B7 Exportiert am " },
  "results.loading_report":               { group: "results", de: "Lade Bericht\u2026" },
  "results.pdf_no_panels_error":          { group: "results", de: "Keine Tab-Panels gefunden. Selektor: {selector}" },
  "results.email_placeholder":            { group: "results", de: "empfaenger@unternehmen.de" },
  "results.errors_card_title":            { group: "results", de: "Hinweise & Fehler" },
  "results.empty_no_analysis":            { group: "results", de: "Noch keine Analyse durchgef\u00FChrt." },
  "results.empty_start_pre":              { group: "results", de: "Starten Sie unter " },
  "results.empty_link_domain":            { group: "results", de: "Domainanalyse" },
  "results.empty_start_mid":              { group: "results", de: " oder " },
  "results.empty_start_post":             { group: "results", de: "." },
  "results.chart_meta_title":             { group: "results", de: "Meta-Titel" },
  "results.chart_meta_desc":              { group: "results", de: "Meta-Beschr." },
  "results.chart_alt_texts":              { group: "results", de: "Alt-Texte" },
  "results.chart_your_site":              { group: "results", de: "Ihre Seite" },
  "results.email_send_error_fallback":    { group: "results", de: "Sendefehler" },
  "results.pdf_no_valid_pages_error":     { group: "results", de: "Keine Seiten konnten gerendert werden. Alle {count} Panels haben leere Canvas." },

  "auth.login_title":           { group: "auth", de: "Admin Login" },
  "auth.login_subtitle":        { group: "auth", de: "Melden Sie sich mit Ihren Zugangsdaten an." },
  "auth.username_label":        { group: "auth", de: "Benutzername" },
  "auth.password_label":        { group: "auth", de: "Passwort" },
  "auth.login_button":          { group: "auth", de: "Anmelden" },
  "auth.login_button_loading":  { group: "auth", de: "Anmelden\u2026" },
  "auth.login_failed":          { group: "auth", de: "Anmeldung fehlgeschlagen" },
  "auth.network_error":         { group: "auth", de: "Netzwerkfehler. Bitte versuchen Sie es erneut." },
  "auth.set_password_title":    { group: "auth", de: "Passwort setzen" },
  "auth.logged_in_as":          { group: "auth", de: "Anmeldung als " },
  "auth.set_password_subtitle": { group: "auth", de: "Bitte setzen Sie Ihr pers\u00F6nliches Passwort, um fortzufahren." },
  "auth.temp_password_label":   { group: "auth", de: "Tempor\u00E4res Passwort" },
  "auth.new_password_label":    { group: "auth", de: "Neues Passwort" },
  "auth.confirm_password_label":{ group: "auth", de: "Passwort best\u00E4tigen" },
  "auth.saving_loading":        { group: "auth", de: "Speichern\u2026" },
  "auth.set_password_button":   { group: "auth", de: "Passwort setzen & anmelden" },
  "auth.pw_mismatch":           { group: "auth", de: "Passw\u00F6rter stimmen nicht \u00FCberein" },
  "auth.policy_not_met":        { group: "auth", de: "Bitte erf\u00FCllen Sie alle Passwortanforderungen" },
  "auth.set_password_failed":   { group: "auth", de: "Fehler beim Setzen des Passworts" },
  "auth.policy_min_length":     { group: "auth", de: "Mindestens 10 Zeichen" },
  "auth.policy_uppercase":      { group: "auth", de: "Gro\u00DFbuchstabe (A\u2013Z)" },
  "auth.policy_lowercase":      { group: "auth", de: "Kleinbuchstabe (a\u2013z)" },
  "auth.policy_digit":          { group: "auth", de: "Ziffer (0\u20139)" },
  "auth.policy_special":        { group: "auth", de: "Sonderzeichen (!@#$%\u2026)" },
  "auth.already_logged_in_title": { group: "auth", de: "Login" },
  "auth.already_logged_in_text":  { group: "auth", de: "Sie sind bereits angemeldet." },
  "auth.go_to_profile_button":    { group: "auth", de: "Zum Profil" },
  "auth.no_active_session":       { group: "auth", de: "Keine aktive Passwort-\u00C4nderungssitzung. Bitte melden Sie sich zuerst an." },
  "auth.go_to_login_button":      { group: "auth", de: "Zum Login" },

  "profile.loading":              { group: "profile", de: "Laden\u2026" },
  "profile.not_logged_in":        { group: "profile", de: "Sie sind nicht angemeldet." },
  "profile.msg_saved":            { group: "profile", de: "\u2713 Gespeichert" },
  "profile.msg_username_updated": { group: "profile", de: "\u2713 Benutzername aktualisiert" },
  "profile.msg_email_updated":    { group: "profile", de: "\u2713 E-Mail aktualisiert" },
  "profile.msg_email_changed":    { group: "profile", de: "\u2713 E-Mail erfolgreich ge\u00E4ndert" },
  "profile.msg_password_changed": { group: "profile", de: "\u2713 Passwort ge\u00E4ndert" },
  "profile.no_mailserver":        { group: "profile", de: "Kein E-Mail-Server konfiguriert \u2013 Ihr Code wird direkt angezeigt:" },
  "profile.code_sent":            { group: "profile", de: "Best\u00E4tigungscode wurde an Ihre aktuelle E-Mail gesendet." },
  "profile.error_generic":        { group: "profile", de: "Fehler" },
  "profile.invalid_code":         { group: "profile", de: "Ung\u00FCltiger Code" },
};
