export const SUPPORTED_LOCALES = ["de", "en"] as const;
export type Locale = typeof SUPPORTED_LOCALES[number];

export interface LabelDef {
  group: string;
  de: string;
}

export const labelDefaults: Record<string, LabelDef> = {
  "welcome.eyebrow":           { group: "welcome", de: "KI-Sichtbarkeit & SEO-Analyse" },
  "welcome.headline_pre":      { group: "welcome", de: "Wie gut findet" },
  "welcome.headline_post":     { group: "welcome", de: "Ihre Website?" },
  "welcome.subline":           { group: "welcome", de: "Der GAIO Analyzer untersucht Ihre B2B-Website auf LLM-Auffindbarkeit und klassische SEO-Grundlagen — und zeigt, was geändert werden muss, damit KI-Systeme Ihr Unternehmen empfehlen." },
  "welcome.label_company":     { group: "welcome", de: "Unternehmensname" },
  "welcome.placeholder_company": { group: "welcome", de: "Muster GmbH" },
  "welcome.placeholder_url":   { group: "welcome", de: "z. B. domain.de oder www.domain.de" },
  "welcome.btn_start":         { group: "welcome", de: "Analyse starten →" },
  "welcome.prefill_prefix":    { group: "welcome", de: "Oder" },
  "welcome.prefill_link":      { group: "welcome", de: "mit KI vorausfüllen" },
  "welcome.prefill_suffix":    { group: "welcome", de: "— Zielgruppen & Wettbewerber werden automatisch ermittelt." },
  "welcome.tile1_title":       { group: "welcome", de: "LLM-Sichtbarkeit messen" },
  "welcome.tile1_desc":        { group: "welcome", de: "Wir simulieren, wie ChatGPT, Gemini und Claude Ihre Website wahrnehmen — und wo Informationen fehlen." },
  "welcome.tile2_title":       { group: "welcome", de: "Wettbewerb vergleichen" },
  "welcome.tile2_desc":        { group: "welcome", de: "Sehen Sie sofort, ob Konkurrenten in denselben KI-Antworten auftauchen — und warum." },
  "welcome.tile3_title":       { group: "welcome", de: "Priorisierte Maßnahmen" },
  "welcome.tile3_desc":        { group: "welcome", de: "Kritisch, hoher Hebel, nachgeordnet — klare Empfehlungen direkt aus der Analyse." },
  "welcome.preview_label":     { group: "welcome", de: "Beispiel-Ergebnis" },
  "welcome.preview_grade":     { group: "welcome", de: "Ausbaufähig" },
  "welcome.preview_desc":      { group: "welcome", de: "So sieht ein typisches Ergebnis aus. Technische Grundlagen stimmen oft — aber für KI-Systeme fehlen verwertbare Inhalte, strukturierte Daten und FAQ-Strukturen." },
  "welcome.demo_seo":          { group: "welcome", de: "Techn. SEO" },
  "welcome.demo_schema":       { group: "welcome", de: "Schema.org" },
  "welcome.demo_content":      { group: "welcome", de: "Inhalt" },
  "welcome.demo_llm":          { group: "welcome", de: "LLM" },

  "html.title":               { group: "html", de: "HTML-Analyse" },
  "html.subtitle":            { group: "html", de: "Einzelne HTML-Seite analysieren." },
  "html.info_single_page":    { group: "html", de: "Wenn Sie diesen Weg wählen, wird nur die einzelne Seite analysiert, die Sie hier bereitstellen. Crawler-abhängige Module werden übersprungen." },
  "html.tab_code":            { group: "html", de: "Code einfügen" },
  "html.tab_upload":          { group: "html", de: "Datei hochladen" },
  "html.placeholder_code":    { group: "html", de: "HTML-Code hier einfügen..." },
  "html.drop_title":          { group: "html", de: "Datei hierher ziehen" },
  "html.drop_subtitle":       { group: "html", de: "oder klicken zum Auswählen" },
  "html.btn_replace":         { group: "html", de: "Ersetzen" },
  "html.btn_start":           { group: "html", de: "Analyse starten" },
  "html.error_file_type":     { group: "html", de: "Nur .html und .htm Dateien werden akzeptiert." },
  "html.error_empty":         { group: "html", de: "Bitte HTML-Code einfügen oder eine Datei hochladen." },
  "html.error_start_failed":  { group: "html", de: "Analyse konnte nicht gestartet werden. Bitte erneut versuchen." },

  "nav.domain_analyse": { group: "nav", de: "Domainanalyse – Basisdaten" },
  "nav.html_analyse":   { group: "nav", de: "HTML-Analyse" },
  "nav.ergebnisse":     { group: "nav", de: "Ergebnisse" },
  "nav.faq":            { group: "nav", de: "FAQ / So funktioniert's" },
  "nav.kontakt":        { group: "nav", de: "Kontakt" },
  "nav.einstellungen":  { group: "nav", de: "Einstellungen" },
  "nav.vergleich":      { group: "nav", de: "Vergleich" },
  "nav.login":          { group: "nav", de: "Login" },
  "nav.server":         { group: "nav", de: "Server" },
  "nav.menu_open":      { group: "nav", de: "Menü öffnen" },

  "domain.subtitle":               { group: "domain", de: "Website crawlen und alle 7 Analysemodule ausführen." },
  "domain.section_company":        { group: "domain", de: "Unternehmen & Website" },
  "domain.label_company":          { group: "domain", de: "Unternehmensname" },
  "domain.tooltip_company":        { group: "domain", de: "Bitte geben Sie die korrekte Unternehmensbezeichnung ein" },
  "domain.label_url":              { group: "domain", de: "Website-URL" },
  "domain.tooltip_url":            { group: "domain", de: "Bitte Ihre hier zu analysierende Website eintragen" },
  "domain.prefill_pending":        { group: "domain", de: "KI analysiert Unternehmen…" },
  "domain.btn_prefill":            { group: "domain", de: "Mit KI vorausfüllen" },
  "domain.prefill_hint":           { group: "domain", de: "KI schlägt Zielgruppen und Wettbewerber automatisch vor —" },
  "domain.prefill_manual":         { group: "domain", de: "manuell ausfüllen" },
  "domain.btn_switch_to_ai":       { group: "domain", de: "← Mit KI vorausfüllen" },
  "domain.pages_title":            { group: "domain", de: "Zu analysierende Unterseiten" },
  "domain.pages_desc":             { group: "domain", de: "Automatisch beim letzten Crawl erkannt. Sie können URLs bearbeiten, neue hinzufügen und die Auswahl anpassen." },
  "domain.pages_count":            { group: "domain", de: "{selected} von {total} ausgewählt" },
  "domain.pages_deselect_all":     { group: "domain", de: "Alle abwählen" },
  "domain.pages_select_all":       { group: "domain", de: "Alle auswählen" },
  "domain.aria_confirm":           { group: "domain", de: "Bestätigen" },
  "domain.aria_cancel":            { group: "domain", de: "Abbrechen" },
  "domain.aria_edit_url":          { group: "domain", de: "URL bearbeiten" },
  "domain.pages_show_less":        { group: "domain", de: "Weniger anzeigen" },
  "domain.pages_show_more":        { group: "domain", de: "{n} weitere anzeigen" },
  "domain.pages_add_url":          { group: "domain", de: "URL hinzufügen" },
  "domain.prefill_success":        { group: "domain", de: "KI-Vorschläge wurden eingefügt. Bitte überprüfen und bei Bedarf anpassen." },
  "domain.prefill_crawl_failed":   { group: "domain", de: "⚠ Website konnte nicht gecrawlt werden — Vorschläge basieren nur auf dem Unternehmensnamen." },
  "domain.prefill_products_label": { group: "domain", de: "Erkannte Produkte / Leistungen:" },
  "domain.section_competitors":    { group: "domain", de: "Wettbewerber-Domains" },
  "domain.tooltip_competitors":    { group: "domain", de: "Die Website-Adresse/n Ihrer wichtigsten Wettbewerber" },
  "domain.aria_open_website":      { group: "domain", de: "Website öffnen" },
  "domain.placeholder_competitor": { group: "domain", de: "z. B. wettbewerber.de" },
  "domain.tooltip_url_unverified": { group: "domain", de: "URL konnte nicht automatisch verifiziert werden — bitte prüfen" },
  "domain.aria_url_verified":      { group: "domain", de: "URL verifiziert" },
  "domain.aria_url_unverified":    { group: "domain", de: "URL nicht verifiziert" },
  "domain.aria_remove":            { group: "domain", de: "Entfernen" },
  "domain.btn_add_competitor":     { group: "domain", de: "Weiteren Wettbewerber hinzufügen" },
  "domain.section_personas":       { group: "domain", de: "Zielgruppen / Käuferpersonas" },
  "domain.tooltip_personas":       { group: "domain", de: "Hier Ihre Zielbranchen und Zielpersonen (Einkäufer, Projektingenieure, R+D…) eintragen" },
  "domain.placeholder_personas":   { group: "domain", de: "z. B. Einkaufsleiter in der Automobilindustrie, Projektingenieure im Maschinenbau, F&E-Verantwortliche..." },
  "domain.error_company_required": { group: "domain", de: "Bitte Unternehmensname eingeben" },
  "domain.error_url_required":     { group: "domain", de: "Bitte Website-URL eingeben" },
  "domain.error_url_invalid":      { group: "domain", de: "Bitte eine gültige URL eingeben (https://...)" },
  "domain.error_prefill_failed":   { group: "domain", de: "KI-Vorausfüllung fehlgeschlagen. Bitte füllen Sie die Felder manuell aus." },
};
