export const SUPPORTED_LOCALES = ["de", "en"] as const;
export type Locale = typeof SUPPORTED_LOCALES[number];

export interface LabelDef {
  group: string;
  de: string;
}

export const labelDefaults: Record<string, LabelDef> = {
  "welcome.eyebrow":           { group: "welcome", de: "KI-Sichtbarkeit & SEO-Analyse" },
  "welcome.headline_pre":      { group: "welcome", de: "Wie gut findet" },
  "welcome.headline_post":     { group: "welcome", de: "Ihre Website?" },
  "welcome.subline":           { group: "welcome", de: "Der GAIO Analyzer untersucht Ihre B2B-Website auf LLM-Auffindbarkeit und klassische SEO-Grundlagen — und zeigt, was geändert werden muss, damit KI-Systeme Ihr Unternehmen empfehlen." },
  "welcome.label_company":     { group: "welcome", de: "Unternehmensname" },
  "welcome.placeholder_company": { group: "welcome", de: "Muster GmbH" },
  "welcome.placeholder_url":   { group: "welcome", de: "z. B. domain.de oder www.domain.de" },
  "welcome.btn_start":         { group: "welcome", de: "Analyse starten →" },
  "welcome.prefill_prefix":    { group: "welcome", de: "Oder" },
  "welcome.prefill_link":      { group: "welcome", de: "mit KI vorausfüllen" },
  "welcome.prefill_suffix":    { group: "welcome", de: "— Zielgruppen & Wettbewerber werden automatisch ermittelt." },
  "welcome.tile1_title":       { group: "welcome", de: "LLM-Sichtbarkeit messen" },
  "welcome.tile1_desc":        { group: "welcome", de: "Wir simulieren, wie ChatGPT, Gemini und Claude Ihre Website wahrnehmen — und wo Informationen fehlen." },
  "welcome.tile2_title":       { group: "welcome", de: "Wettbewerb vergleichen" },
  "welcome.tile2_desc":        { group: "welcome", de: "Sehen Sie sofort, ob Konkurrenten in denselben KI-Antworten auftauchen — und warum." },
  "welcome.tile3_title":       { group: "welcome", de: "Priorisierte Maßnahmen" },
  "welcome.tile3_desc":        { group: "welcome", de: "Kritisch, hoher Hebel, nachgeordnet — klare Empfehlungen direkt aus der Analyse." },
  "welcome.preview_label":     { group: "welcome", de: "Beispiel-Ergebnis" },
  "welcome.preview_grade":     { group: "welcome", de: "Ausbaufähig" },
  "welcome.preview_desc":      { group: "welcome", de: "So sieht ein typisches Ergebnis aus. Technische Grundlagen stimmen oft — aber für KI-Systeme fehlen verwertbare Inhalte, strukturierte Daten und FAQ-Strukturen." },
  "welcome.demo_seo":          { group: "welcome", de: "Techn. SEO" },
  "welcome.demo_schema":       { group: "welcome", de: "Schema.org" },
  "welcome.demo_content":      { group: "welcome", de: "Inhalt" },
  "welcome.demo_llm":          { group: "welcome", de: "LLM" },

  "html.title":               { group: "html", de: "HTML-Analyse" },
  "html.subtitle":            { group: "html", de: "Einzelne HTML-Seite analysieren." },
  "html.info_single_page":    { group: "html", de: "Wenn Sie diesen Weg wählen, wird nur die einzelne Seite analysiert, die Sie hier bereitstellen. Crawler-abhängige Module werden übersprungen." },
  "html.tab_code":            { group: "html", de: "Code einfügen" },
  "html.tab_upload":          { group: "html", de: "Datei hochladen" },
  "html.placeholder_code":    { group: "html", de: "HTML-Code hier einfügen..." },
  "html.drop_title":          { group: "html", de: "Datei hierher ziehen" },
  "html.drop_subtitle":       { group: "html", de: "oder klicken zum Auswählen" },
  "html.btn_replace":         { group: "html", de: "Ersetzen" },
  "html.btn_start":           { group: "html", de: "Analyse starten" },
  "html.error_file_type":     { group: "html", de: "Nur .html und .htm Dateien werden akzeptiert." },
  "html.error_empty":         { group: "html", de: "Bitte HTML-Code einfügen oder eine Datei hochladen." },
  "html.error_start_failed":  { group: "html", de: "Analyse konnte nicht gestartet werden. Bitte erneut versuchen." },

  "nav.domain_analyse": { group: "nav", de: "Domainanalyse – Basisdaten" },
  "nav.html_analyse":   { group: "nav", de: "HTML-Analyse" },
  "nav.ergebnisse":     { group: "nav", de: "Ergebnisse" },
  "nav.faq":            { group: "nav", de: "FAQ / So funktioniert's" },
  "nav.kontakt":        { group: "nav", de: "Kontakt" },
  "nav.einstellungen":  { group: "nav", de: "Einstellungen" },
  "nav.vergleich":      { group: "nav", de: "Vergleich" },
  "nav.login":          { group: "nav", de: "Login" },
  "nav.server":         { group: "nav", de: "Server" },
  "nav.menu_open":      { group: "nav", de: "Menü öffnen" },

  "domain.subtitle":               { group: "domain", de: "Website crawlen und alle 7 Analysemodule ausführen." },
  "domain.section_company":        { group: "domain", de: "Unternehmen & Website" },
  "domain.label_company":          { group: "domain", de: "Unternehmensname" },
  "domain.tooltip_company":        { group: "domain", de: "Bitte geben Sie die korrekte Unternehmensbezeichnung ein" },
  "domain.label_url":              { group: "domain", de: "Website-URL" },
  "domain.tooltip_url":            { group: "domain", de: "Bitte Ihre hier zu analysierende Website eintragen" },
  "domain.prefill_pending":        { group: "domain", de: "KI analysiert Unternehmen…" },
  "domain.btn_prefill":            { group: "domain", de: "Mit KI vorausfüllen" },
  "domain.prefill_hint":           { group: "domain", de: "KI schlägt Zielgruppen und Wettbewerber automatisch vor —" },
  "domain.prefill_manual":         { group: "domain", de: "manuell ausfüllen" },
  "domain.btn_switch_to_ai":       { group: "domain", de: "← Mit KI vorausfüllen" },
  "domain.pages_title":            { group: "domain", de: "Zu analysierende Unterseiten" },
  "domain.pages_desc":             { group: "domain", de: "Automatisch beim letzten Crawl erkannt. Sie können URLs bearbeiten, neue hinzufügen und die Auswahl anpassen." },
  "domain.pages_count":            { group: "domain", de: "{selected} von {total} ausgewählt" },
  "domain.pages_deselect_all":     { group: "domain", de: "Alle abwählen" },
  "domain.pages_select_all":       { group: "domain", de: "Alle auswählen" },
  "domain.aria_confirm":           { group: "domain", de: "Bestätigen" },
  "domain.aria_cancel":            { group: "domain", de: "Abbrechen" },
  "domain.aria_edit_url":          { group: "domain", de: "URL bearbeiten" },
  "domain.pages_show_less":        { group: "domain", de: "Weniger anzeigen" },
  "domain.pages_show_more":        { group: "domain", de: "{n} weitere anzeigen" },
  "domain.pages_add_url":          { group: "domain", de: "URL hinzufügen" },
  "domain.prefill_success":        { group: "domain", de: "KI-Vorschläge wurden eingefügt. Bitte überprüfen und bei Bedarf anpassen." },
  "domain.prefill_crawl_failed":   { group: "domain", de: "⚠ Website konnte nicht gecrawlt werden — Vorschläge basieren nur auf dem Unternehmensnamen." },
  "domain.prefill_products_label": { group: "domain", de: "Erkannte Produkte / Leistungen:" },
  "domain.section_competitors":    { group: "domain", de: "Wettbewerber-Domains" },
  "domain.tooltip_competitors":    { group: "domain", de: "Die Website-Adresse/n Ihrer wichtigsten Wettbewerber" },
  "domain.aria_open_website":      { group: "domain", de: "Website öffnen" },
  "domain.placeholder_competitor": { group: "domain", de: "z. B. wettbewerber.de" },
  "domain.tooltip_url_unverified": { group: "domain", de: "URL konnte nicht automatisch verifiziert werden — bitte prüfen" },
  "domain.aria_url_verified":      { group: "domain", de: "URL verifiziert" },
  "domain.aria_url_unverified":    { group: "domain", de: "URL nicht verifiziert" },
  "domain.aria_remove":            { group: "domain", de: "Entfernen" },
  "domain.btn_add_competitor":     { group: "domain", de: "Weiteren Wettbewerber hinzufügen" },
  "domain.section_personas":       { group: "domain", de: "Zielgruppen / Käuferpersonas" },
  "domain.tooltip_personas":       { group: "domain", de: "Hier Ihre Zielbranchen und Zielpersonen (Einkäufer, Projektingenieure, R+D…) eintragen" },
  "domain.placeholder_personas":   { group: "domain", de: "z. B. Einkaufsleiter in der Automobilindustrie, Projektingenieure im Maschinenbau, F&E-Verantwortliche..." },
  "domain.error_company_required": { group: "domain", de: "Bitte Unternehmensname eingeben" },
  "domain.error_url_required":     { group: "domain", de: "Bitte Website-URL eingeben" },
  "domain.error_url_invalid":      { group: "domain", de: "Bitte eine gültige URL eingeben (https://...)" },
  "domain.error_prefill_failed":   { group: "domain", de: "KI-Vorausfüllung fehlgeschlagen. Bitte füllen Sie die Felder manuell aus." },

  "faq.subtitle":                    { group: "faq", de: "Alles über die Analyse-Methodik und Score-Interpretation." },
  "faq.section_what":                { group: "faq", de: "Was analysiert dieses Tool?" },
  "faq.what_desc":                   { group: "faq", de: "GAIO Analyzer untersucht B2B-Industriewebsites auf ihre Auffindbarkeit durch KI-Sprachmodelle (LLMs) sowie auf klassische SEO-Grundlagen. Ziel ist es, konkrete Handlungsempfehlungen zu liefern, die sowohl die Suchmaschinen-Indexierung als auch die Zitierwahrscheinlichkeit durch KI-Assistenten wie ChatGPT, Gemini oder Perplexity erhöhen." },
  "faq.section_modules":             { group: "faq", de: "Die Analyse-Module im Überblick" },
  "faq.col_module":                  { group: "faq", de: "Modul" },
  "faq.col_checked":                 { group: "faq", de: "Was wird geprüft" },
  "faq.col_why":                     { group: "faq", de: "Warum es wichtig ist" },
  "faq.mod1_name":                   { group: "faq", de: "Technische SEO-Basis" },
  "faq.mod1_check":                  { group: "faq", de: "HTTP-Antwortzeit, HTTPS, robots.txt, llms.txt, Sitemap (.xml oder /sitemap<sup>*</sup>), Canonical-Tags, hreflang, Meta-Titel und -Beschreibungen, Alt-Texte, Mobile-Viewport" },
  "faq.mod1_why":                    { group: "faq", de: "Grundvoraussetzung für Indexierung durch Suchmaschinen und LLM-Crawler" },
  "faq.mod2_name":                   { group: "faq", de: "Strukturierte Daten (Schema.org)" },
  "faq.mod2_check":                  { group: "faq", de: "JSON-LD, Microdata, RDFa — Typen: Organization, Product, FAQPage, BreadcrumbList u.a." },
  "faq.mod2_why":                    { group: "faq", de: "Maschinenlesbare Fakten erhöhen die Wahrscheinlichkeit, dass LLMs korrekte und vollständige Antworten generieren" },
  "faq.mod3_name":                   { group: "faq", de: "Heading-Struktur" },
  "faq.mod3_check":                  { group: "faq", de: "H1/H2/H3-Hierarchie, Keyword-Präsenz in Überschriften" },
  "faq.mod3_why":                    { group: "faq", de: "Strukturierte Inhalte werden von LLMs bevorzugt als Quellen verarbeitet" },
  "faq.mod4_name":                   { group: "faq", de: "Inhaltliche Relevanz (KI-gestützt)" },
  "faq.mod4_check":                  { group: "faq", de: "Vorhandensein von Anwendungsszenarien, technischer Tiefe, Käufer-Fragetypen" },
  "faq.mod4_why":                    { group: "faq", de: "LLMs zitieren Seiten häufiger, wenn diese echte Nutzerfragen vollständig beantworten" },
  "faq.mod5_name":                   { group: "faq", de: "FAQ-Qualität" },
  "faq.mod5_check":                  { group: "faq", de: "Erkannte FAQ-Strukturen, Frageformulierung, Antworttiefe" },
  "faq.mod5_why":                    { group: "faq", de: "FAQPage-Schema ist einer der stärksten Einzelhebel für LLM-Sichtbarkeit" },
  "faq.mod6_name":                   { group: "faq", de: "LLM-Sichtbarkeitssimulation" },
  "faq.mod6_check":                  { group: "faq", de: "Generierte Käuferfragen + prognostizierte Antwortqualität auf Basis des vorhandenen Contents" },
  "faq.mod6_why":                    { group: "faq", de: "Zeigt direkt, welche Informationslücken LLMs bei Anfragen zu Ihrem Unternehmen haben" },
  "faq.sitemap_title":               { group: "faq", de: "sitemap.xml vs. /sitemap — was wird geprüft und warum beides relevant ist" },
  "faq.sitemap_desc":                { group: "faq", de: "Der GAIO Analyzer sucht zuerst nach einer maschinenlesbaren sitemap.xml (inkl. sitemap_index.xml sowie in robots.txt deklarierten Sitemap-Pfaden). Falls keine XML-Sitemap gefunden wird, sucht er nach einer HTML-Sitemap unter gängigen Pfaden wie /sitemap, /sitemap.html oder /seitenübersicht." },
  "faq.sitemap_col_criterion":       { group: "faq", de: "Kriterium" },
  "faq.sitemap_row_purpose_label":   { group: "faq", de: "Zweck" },
  "faq.sitemap_row_purpose_xml":     { group: "faq", de: "Maschinenlesbare Übergabe an Crawler; enthält lastmod, priority, changefreq" },
  "faq.sitemap_row_purpose_html":    { group: "faq", de: "HTML-Seite mit internen Links zu allen wichtigen Seiten; für Menschen und Crawler lesbar" },
  "faq.sitemap_row_google_label":    { group: "faq", de: "Google / Search Console" },
  "faq.sitemap_row_google_xml":      { group: "faq", de: "✅ Direkt einreichbar; Indexierungsstatus in Search Console sichtbar" },
  "faq.sitemap_row_google_html":     { group: "faq", de: "❌ Nicht einreichbar; kann aber selbst indexiert werden" },
  "faq.sitemap_row_links_label":     { group: "faq", de: "Interne Verlinkung" },
  "faq.sitemap_row_links_xml":       { group: "faq", de: "❌ Wird nicht als Linkquelle gewertet" },
  "faq.sitemap_row_links_html":      { group: "faq", de: "✅ Interne Links zählen als Linkgraph und stärken PageRank-Verteilung" },
  "faq.sitemap_row_llm_train_label": { group: "faq", de: "LLM-Training-Crawler" },
  "faq.sitemap_row_llm_train_xml":   { group: "faq", de: "⚠️ Wird von manchen Crawlern (z.B. Common Crawl) gelesen, aber nicht als Content aufgenommen" },
  "faq.sitemap_row_llm_train_html":  { group: "faq", de: "✅ HTML-Links werden direkt als Crawl-Einstiegspunkte verwertet — für Link-Following-Crawler direkter verwertbar" },
  "faq.sitemap_row_rag_label":       { group: "faq", de: "LLM-Live-Retrieval (RAG)" },
  "faq.sitemap_row_rag_xml":         { group: "faq", de: "✅ Bessere XML-Indexierung = mehr Seiten im Suchindex = mehr Zitierchancen" },
  "faq.sitemap_row_rag_html":        { group: "faq", de: "✅ Kann selbst gecrawlt und als Linking-Hub genutzt werden" },
  "faq.sitemap_row_scale_label":     { group: "faq", de: "Skalierung" },
  "faq.sitemap_row_scale_xml":       { group: "faq", de: "✅ Bis 50.000 URLs; erweiterbar via Sitemap-Index; Spezialformate für Bilder, Videos, News" },
  "faq.sitemap_row_scale_html":      { group: "faq", de: "⚠️ Bei großen Sites schwer wartbar; kein Ersatz für sitemap.xml" },
  "faq.sitemap_recommendation":      { group: "faq", de: "Empfehlung: sitemap.xml und HTML-Sitemap schließen sich nicht aus — sie erfüllen unterschiedliche Funktionen. sitemap.xml ist für die Google-Indexierung unverzichtbar. Eine gepflegte HTML-Sitemap (/sitemap) hat zusätzlichen Wert als internes Verlinkungshub und als Crawl-Einstiegspunkt für LLM-Trainingscrawler — aber nur als Ergänzung, nicht als Ersatz." },
  "faq.section_weights":             { group: "faq", de: "Score-Gewichtung (Gesamt-GAIO-Score)" },
  "faq.weight_schema":               { group: "faq", de: "Strukturierte Daten" },
  "faq.weight_content":              { group: "faq", de: "Inhaltliche Relevanz" },
  "faq.weight_llm":                  { group: "faq", de: "LLM-Sichtbarkeit" },
  "faq.weight_tech":                 { group: "faq", de: "Technische SEO-Basis" },
  "faq.weight_faq":                  { group: "faq", de: "FAQ-Qualität" },
  "faq.weight_heading":              { group: "faq", de: "Heading-Struktur" },
  "faq.section_scores":              { group: "faq", de: "Score-Interpretation" },
  "faq.score_col_score":             { group: "faq", de: "Score" },
  "faq.score_col_rating":            { group: "faq", de: "Bewertung" },
  "faq.score_col_meaning":           { group: "faq", de: "Bedeutung" },
  "faq.score_critical_label":        { group: "faq", de: "Kritisch" },
  "faq.score_critical_desc":         { group: "faq", de: "Grundlegende Defizite — LLMs können diese Website kaum als Quelle nutzen" },
  "faq.score_improving_label":       { group: "faq", de: "Ausbaufähig" },
  "faq.score_improving_desc":        { group: "faq", de: "Technische Basis vorhanden, aber inhaltliche Lücken limitieren die LLM-Sichtbarkeit erheblich" },
  "faq.score_solid_label":           { group: "faq", de: "Solide" },
  "faq.score_solid_desc":            { group: "faq", de: "Gute Ausgangsbasis — gezielte Maßnahmen können die Sichtbarkeit spürbar steigern" },
  "faq.score_strong_label":          { group: "faq", de: "Stark" },
  "faq.score_strong_desc":           { group: "faq", de: "Überdurchschnittlich gut aufgestellt; Feinoptimierung empfohlen" },
  "faq.score_excellent_label":       { group: "faq", de: "Exzellent" },
  "faq.score_excellent_desc":        { group: "faq", de: "Best-in-class LLM-Readiness" },
  "faq.section_priority":            { group: "faq", de: "Empfehlungs-Priorisierung" },
  "faq.priority_desc":               { group: "faq", de: "Jede Analyse erzeugt priorisierte Handlungsempfehlungen in drei Stufen:" },
  "faq.priority_critical_desc":      { group: "faq", de: "Fundamentale Fehler, die sofort behoben werden müssen (z. B. fehlendes HTTPS, keine strukturierten Daten, kein H1)." },
  "faq.priority_high_label":         { group: "faq", de: "Hoher Hebel" },
  "faq.priority_high_desc":          { group: "faq", de: "Maßnahmen mit dem größten Wirkungspotenzial (z. B. fehlende FAQPage-Schema, dünne Produktbeschreibungen, fehlende Anwendungsszenarien)." },
  "faq.priority_low_label":          { group: "faq", de: "Nachgeordnet" },
  "faq.priority_low_desc":           { group: "faq", de: "Optimierungen für nach der Erstbereinigung (z. B. Meta-Description-Länge, Alt-Text-Lücken)." },
  "faq.section_accuracy":            { group: "faq", de: "Hinweise zur Genauigkeit" },
  "faq.accuracy_desc":               { group: "faq", de: "Scores basieren auf einer automatisierten Analyse und stellen Annäherungswerte dar. Wettbewerber-Scores beruhen auf einer Stichprobe (Startseite + max. 3 Unterseiten). Die LLM-Sichtbarkeitssimulation verwendet Claude (Anthropic) und spiegelt keine garantierten Rankingfaktoren wider. Alle Empfehlungen sollten mit einem Experten validiert werden." },
};
